const $=id=>document.getElementById(id);
const constellations=[
 ['Grande Ourse',11.1,55,'✦'],['Petite Ourse',15.0,78,'✧'],['Cassiopée',1.0,60,'W'],['Céphée',22.0,70,'⬠'],['Dragon',17.0,65,'∿'],['Girafe',6.0,70,'⌁'],['Lynx',8.0,45,'／'],['Chiens de chasse',13.0,40,'⋰'],['Bouvier',14.7,30,'◇'],['Couronne boréale',15.8,30,'⌒'],['Hercule',17.2,30,'H'],['Lyre',18.8,36,'◈'],['Cygne',20.5,42,'†'],['Aigle',19.7,5,'⌁'],['Dauphin',20.7,12,'◊'],['Pégase',22.7,20,'□'],['Andromède',0.8,38,'⌁'],['Persée',3.3,45,'Y'],['Cocher',6.0,42,'⬡'],['Taureau',4.6,18,'V'],['Orion',5.6,2,'⋈'],['Gémeaux',7.1,22,'Ⅱ'],['Cancer',8.7,20,'Y'],['Lion',10.7,15,'♌'],['Vierge',13.4,-5,'♍'],['Balance',15.2,-15,'⚖'],['Scorpion',16.9,-30,'S'],['Sagittaire',19.0,-25,'⌁'],['Capricorne',21.0,-20,'V'],['Verseau',22.3,-10,'≈'],['Poissons',0.7,10,'⌁'],['Bélier',2.6,20,'⌒'],['Ophiuchus',17.4,-8,'U'],['Baleine',1.7,-10,'⌁'],['Grand Chien',6.8,-22,'Y'],['Petit Chien',7.6,5,'⌁'],['Hydre',10.5,-20,'∿'],['Corbeau',12.4,-18,'◇'],['Éridan',3.5,-22,'∿']
];
let current={lat:null,lon:null,name:''};
const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI,clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function julian(d){return d.getTime()/86400000+2440587.5}
function sidereal(d,lon){const D=julian(d)-2451545;return ((18.697374558+24.06570982441908*D+lon/15)%24+24)%24}
function altitude(ra,dec,lat,lon,date){const ha=rad((sidereal(date,lon)-ra)*15);return deg(Math.asin(Math.sin(rad(lat))*Math.sin(rad(dec))+Math.cos(rad(lat))*Math.cos(rad(dec))*Math.cos(ha)))}
function moonIllumination(date){const syn=29.53058867,known=Date.UTC(2000,0,6,18,14),age=((date-known)/86400000%syn+syn)%syn;return Math.round((1-Math.cos(2*Math.PI*age/syn))/2*100)}
function solarTimes(date,lat,lon){const start=new Date(date);start.setHours(0,0,0,0);const n=Math.floor(julian(start)-2451545+0.0008),Jstar=n-lon/360;const M=rad((357.5291+0.98560028*Jstar)%360);const C=1.9148*Math.sin(M)+.02*Math.sin(2*M)+.0003*Math.sin(3*M);const lambda=rad((deg(M)+C+180+102.9372)%360);const Jtrans=2451545+Jstar+.0053*Math.sin(M)-.0069*Math.sin(2*lambda);const delta=Math.asin(Math.sin(lambda)*Math.sin(rad(23.44)));const h=rad(-18);const cosw=(Math.sin(h)-Math.sin(rad(lat))*Math.sin(delta))/(Math.cos(rad(lat))*Math.cos(delta));if(Math.abs(cosw)>1)return null;const w=deg(Math.acos(cosw))/360;return{dusk:new Date((Jtrans+w-2440587.5)*86400000),dawn:new Date((Jtrans-w+1-2440587.5)*86400000)}}
function fmtHour(d){return d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
async function citySearch(name){const u=`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(name)}&count=1&language=fr&format=json`;const r=await fetch(u);if(!r.ok)throw Error('Recherche indisponible');const j=await r.json();if(!j.results?.length)throw Error('Ville introuvable');const x=j.results[0];return{lat:x.latitude,lon:x.longitude,name:[x.name,x.admin1].filter(Boolean).join(', ')}}
async function reverseName(lat,lon){try{const r=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${lat}&longitude=${lon}&localityLanguage=fr`);const j=await r.json();return j.city||j.locality||j.principalSubdivision||'Ma position'}catch{return'Ma position'}}
async function loadWeather(lat,lon){const params=new URLSearchParams({latitude:lat,longitude:lon,hourly:'cloud_cover,relative_humidity_2m,precipitation_probability,visibility',timezone:'auto',forecast_days:'2'});const r=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`);if(!r.ok)throw Error('Prévisions météo indisponibles');return r.json()}
function hourScore(c,h,i,moon){const cloud=h.cloud_cover[i]??100,rain=h.precipitation_probability[i]??0,hum=h.relative_humidity_2m[i]??100,vis=h.visibility[i]??10000;return Math.round(clamp(100-cloud*.72-rain*.3-Math.max(0,hum-82)*.55-Math.max(0,8000-vis)/500-moon*.08,0,100))}
function describeScore(s){if(s>=78)return['Excellent pour observer','Le ciel devrait offrir de très belles conditions.'];if(s>=60)return['Bon pour observer','Quelques passages nuageux possibles, mais la nuit reste prometteuse.'];if(s>=38)return['Conditions moyennes','Des éclaircies sont possibles, surveillez l’évolution des nuages.'];return['Peu favorable','Les nuages ou l’humidité limiteront fortement l’observation.']}
function renderConstellations(){const now=new Date();const visible=constellations.map(c=>({...c,name:c[0],alt:altitude(c[1],c[2],current.lat,current.lon,now),sym:c[3]})).filter(c=>c.alt>8).sort((a,b)=>b.alt-a.alt);$('constellationCount').textContent=visible.length;$('constellationList').innerHTML=visible.slice(0,16).map(c=>{const quality=c.alt>45?'Très haute':c.alt>25?'Bien placée':'Basse';return`<article class="constellation"><span class="constellation-symbol">${c.sym}</span><div><h3>${c.name}</h3><p>${quality}</p></div><div class="altitude"><strong>${Math.round(c.alt)}°</strong><span>altitude</span><div class="alt-bar"><i style="width:${clamp(c.alt/90*100,0,100)}%"></i></div></div></article>`}).join('')}
function render(weather){const h=weather.hourly,now=new Date(),today=now.toISOString().slice(0,10);let night=solarTimes(now,current.lat,current.lon);let candidates=[];for(let i=0;i<h.time.length;i++){const d=new Date(h.time[i]);const hour=d.getHours();if((h.time[i].startsWith(today)&&hour>=20)||(d>now&&d-now<16*3600000&&hour<=6))candidates.push({i,d})}if(!candidates.length)candidates=h.time.map((x,i)=>({i,d:new Date(x)})).filter(x=>x.d>now).slice(0,10);const moon=moonIllumination(now);candidates.forEach(x=>x.score=hourScore(null,h,x.i,moon));const best=candidates.reduce((a,b)=>b.score>a.score?b:a,candidates[0]);const top=candidates.filter(x=>x.score>=best.score-8);const avg=Math.round(candidates.reduce((s,x)=>s+x.score,0)/candidates.length);const verdict=describeScore(avg);$('scoreValue').textContent=avg;$('scoreRing').style.background=`conic-gradient(${avg>=60?'var(--green)':avg>=38?'var(--yellow)':'var(--red)'} ${avg*3.6}deg,#22304d 0deg)`;$('verdictText').textContent=verdict[0];$('verdictDetail').textContent=verdict[1];$('bestWindow').textContent=`${fmtHour(top[0].d)} — ${fmtHour(new Date(top[top.length-1].d.getTime()+3600000))}`;$('cloudValue').textContent=`${h.cloud_cover[best.i]} %`;$('cloudHint').textContent=h.cloud_cover[best.i]<25?'ciel peu nuageux':h.cloud_cover[best.i]<60?'passages nuageux':'très couvert';$('moonValue').textContent=`${moon} %`;$('humidityValue').textContent=`${h.relative_humidity_2m[best.i]} %`;$('humidityHint').textContent=h.relative_humidity_2m[best.i]>88?'risque de brume':'air assez sec';$('rainValue').textContent=`${Math.max(...candidates.map(x=>h.precipitation_probability[x.i]??0))} %`;$('timeline').innerHTML=candidates.slice(0,8).map(x=>{const color=x.score>=60?'var(--green)':x.score>=38?'var(--yellow)':'var(--red)';return`<div class="hour"><time>${x.d.getHours()} h</time><div class="bar-wrap"><div class="bar" style="height:${x.score}%;background:${color}"></div></div><strong>${x.score}</strong></div>`}).join('');$('nightInfo').textContent=night?`Nuit astronomique : ${fmtHour(night.dusk)} — ${fmtHour(night.dawn)}`:'Pas de nuit astronomique complète à cette latitude';renderConstellations()}
async function useLocation(loc){current=loc;$('locationName').textContent=loc.name;$('setupStatus').textContent='Chargement des prévisions…';try{const data=await loadWeather(loc.lat,loc.lon);$('setupCard').hidden=true;$('dashboard').hidden=false;render(data);localStorage.setItem('astrociel-location',JSON.stringify(loc))}catch(e){$('setupStatus').textContent=e.message}}
$('gpsButton').addEventListener('click',()=>{if(!navigator.geolocation){$('setupStatus').textContent='La géolocalisation n’est pas disponible.';return}$('setupStatus').textContent='Recherche de votre position…';navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude,name=await reverseName(lat,lon);useLocation({lat,lon,name})},()=>{$('setupStatus').textContent='Position refusée. Recherchez une ville ci-dessous.'},{enableHighAccuracy:false,timeout:10000})});
$('searchForm').addEventListener('submit',async e=>{e.preventDefault();$('setupStatus').textContent='Recherche…';try{useLocation(await citySearch($('cityInput').value.trim()))}catch(err){$('setupStatus').textContent=err.message}});
$('locationButton').addEventListener('click',()=>{$('setupCard').hidden=false;$('dashboard').hidden=true;$('setupCard').scrollIntoView({behavior:'smooth'})});
$('dateLabel').textContent=`CE SOIR · ${new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}).toUpperCase()}`;
try{const saved=JSON.parse(localStorage.getItem('astrociel-location'));if(saved?.lat)useLocation(saved)}catch{}

if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  Promise.resolve(document.modelContext.registerTool({
    name:'show_astronomy_forecast_for_city',title:'Afficher les prévisions astronomiques',
    description:'Recherche une ville puis affiche dans AstroCiel les conditions d’observation et les constellations visibles.',
    inputSchema:{type:'object',properties:{city:{type:'string',minLength:2}},required:['city'],additionalProperties:false},
    annotations:{readOnlyHint:false,untrustedContentHint:true},
    async execute(input){if(!input||typeof input.city!=='string'||input.city.trim().length<2)throw Error('Une ville valide est requise.');const loc=await citySearch(input.city.trim());await useLocation(loc);return{city:loc.name,latitude:loc.lat,longitude:loc.lon,status:'displayed'}}
  },{signal:lifecycle.signal})).catch(()=>{});
}
